import * as Types from './types'

export const DEFAULT_TEXT_LAYOUT: Types.TextLayout = {
    left: 20,
    top: 20,
    fontSize: 30,
    color: '#ffffff',
    width: 20,
    height: 10,
    textAlign: 'center',
}

export const DEFAULT_STATE: Omit<
    Types.State,
    'selectedLayoutCollection' | 'getRacer' | 'getLayout' | 'activeLayout'
> = {
    localVersion: '0.0.2',
    prizePool: 0,
    commentators: '',
    selectedLayoutCollectionId: '',
    activeLayoutId: '',
    activeRacers: ['', '', '', '', '', '', ''],
    racers: {},
    highlightedRacerId: '',
    layoutLibrary: {
        '4 Person Race': {
            name: '4 Person Race',
            racers: 4,
            layouts: {
                'All Racers': {
                    name: 'All Racers',
                    background:
                        'https://istation64.com/racelayout/assets/4.jpg',
                    positions: {
                        prizePool: {
                            color: '#ffffff',
                            fontSize: 30,
                            textAlign: 'center',
                            left: 35,
                            top: 7.654320987654321,
                            height: 7.654320987654321,
                            width: 30,
                        },
                        commentators: {
                            color: '#ffffff',
                            fontSize: 30,
                            textAlign: 'center',
                            left: 34.86111111111111,
                            top: 21.728395061728396,
                            height: 14.320987654320987,
                            width: 30.416666666666664,
                        },
                        places: [
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 35.55555555555556,
                                top: 44.19753086419753,
                                height: 6.91358024691358,
                                width: 29.86111111111111,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 35.55555555555556,
                                top: 58.2716049382716,
                                height: 6.666666666666667,
                                width: 29.166666666666668,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 39.166666666666664,
                                top: 64.93827160493827,
                                height: 5.432098765432099,
                                width: 25.972222222222225,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 39.72222222222222,
                                top: 71.5,
                                height: 6.172839506172839,
                                width: 25.27777777777778,
                            },
                        ],
                        racers: [
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 6.388888888888888,
                                top: 0.495,
                                height: 7.4,
                                width: 26.2,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 67.5,
                                top: 0.495,
                                height: 7.4,
                                width: 26.2,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 6.666666666666667,
                                top: 50.5,
                                height: 7.4,
                                width: 26.2,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 67.5,
                                top: 50.5,
                                height: 7.4,
                                width: 26.2,
                            },
                        ],
                        highlight: [],
                    },
                },
                Highlight: {
                    name: 'Highlight',
                    background:
                        'https://istation64.com/racelayout/assets/4h.png',
                    positions: {
                        prizePool: {
                            left: 1.85,
                            top: 14.9,
                            fontSize: 30,
                            color: '#ffffff',
                            width: 18.6,
                            height: 9.5,
                            textAlign: 'center',
                        },
                        commentators: {
                            left: 1.85,
                            top: 29.8,
                            fontSize: 30,
                            color: '#ffffff',
                            width: 18.6,
                            height: 39.6,
                            textAlign: 'center',
                        },
                        places: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                        racers: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                        highlight: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                    },
                },
            },
        },
        '5 Person Race': {
            name: '5 Person Race',
            racers: 5,
            layouts: {
                'All Racers': {
                    name: 'All Racers',
                    background:
                        'https://istation64.com/racelayout/assets/5.jpg',
                    positions: {
                        prizePool: {
                            color: '#ffffff',
                            fontSize: 30,
                            textAlign: 'center',
                            left: 52.8,
                            top: 38.76543209876544,
                            height: 9.62962962962963,
                            width: 12.1,
                        },
                        commentators: {
                            color: '#ffffff',
                            fontSize: 30,
                            textAlign: 'center',
                            left: 35.41666666666667,
                            top: 5,
                            height: 10.123456790123457,
                            width: 29.1,
                        },
                        places: [
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 44.72222222222222,
                                top: 16.049382716049383,
                                height: 4.197530864197531,
                                width: 20.416666666666668,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 45,
                                top: 20.246913580246915,
                                height: 4.691358024691358,
                                width: 20,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 44.72222222222222,
                                top: 24.691358024691358,
                                height: 4.691358024691358,
                                width: 20.27777777777778,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 45.13888888888889,
                                top: 28.888888888888886,
                                height: 4.691358024691358,
                                width: 20,
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                        racers: [
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 5.416666666666667,
                                top: 0.24691358024691357,
                                height: 7.5,
                                width: 27.916666666666668,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 68.05555555555556,
                                top: 0.24691358024691357,
                                height: 7.5,
                                width: 25.972222222222225,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 2.38,
                                top: 50.5,
                                height: 7.35,
                                width: 26.2,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 36.80555555555556,
                                top: 50.5,
                                height: 7.35,
                                width: 26.2,
                            },
                            {
                                color: '#ffffff',
                                fontSize: 30,
                                textAlign: 'center',
                                left: 71.5,
                                top: 50.5,
                                height: 7.35,
                                width: 26.2,
                            },
                        ],
                        highlight: [],
                    },
                },
                Highlight: {
                    name: 'Highlight',
                    background:
                        'https://istation64.com/racelayout/assets/5h.png',
                    positions: {
                        prizePool: {
                            left: 20,
                            top: 20,
                            fontSize: 30,
                            color: '#ffffff',
                            width: 20,
                            height: 10,
                            textAlign: 'center',
                        },
                        commentators: {
                            left: 20,
                            top: 20,
                            fontSize: 30,
                            color: '#ffffff',
                            width: 20,
                            height: 10,
                            textAlign: 'center',
                        },
                        places: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                        racers: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                        highlight: [
                            {
                                left: 20,
                                top: 20,
                                fontSize: 30,
                                color: '#ffffff',
                                width: 20,
                                height: 10,
                                textAlign: 'center',
                            },
                        ],
                    },
                },
            },
        },
    },
}
